DEBUG - 2025-02-15 14:54:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-02-15 14:54:46 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
[Method: GET, Route: /]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Home.php(36): view('login')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-02-15 14:55:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-02-15 14:55:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-02-15 14:58:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-02-15 15:17:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-02-15 15:33:10 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption in C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php:78
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 78)
#1 C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php(78): pg_connect('host=172.16.225...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\ci4\app\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\app\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
#7 C:\xampp\htdocs\ci4\system\Config\Factories.php(235): Config\Database->__construct()
#8 C:\xampp\htdocs\ci4\system\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', Array)
#9 C:\xampp\htdocs\ci4\system\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', Array)
#10 C:\xampp\htdocs\ci4\system\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
#11 C:\xampp\htdocs\ci4\system\Database\Config.php(63): config('Config\\Database')
#12 C:\xampp\htdocs\ci4\app\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
#13 C:\xampp\htdocs\ci4\app\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
#14 C:\xampp\htdocs\ci4\app\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
#15 C:\xampp\htdocs\ci4\app\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
#16 C:\xampp\htdocs\ci4\system\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
#17 C:\xampp\htdocs\ci4\system\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
#18 C:\xampp\htdocs\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 C:\xampp\htdocs\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 C:\xampp\htdocs\ci4\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}
CRITICAL - 2025-02-15 15:33:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption
[Method: GET, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "company_database_config"
WHERE "company_name" = :company_name:', [...], false)
 3 APPPATH\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
 5 SYSTEMPATH\Config\Factories.php(235): Config\Database->__construct()
 6 SYSTEMPATH\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', [])
 7 SYSTEMPATH\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
 9 SYSTEMPATH\Database\Config.php(63): config('Config\\Database')
10 APPPATH\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
11 APPPATH\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
12 APPPATH\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
13 APPPATH\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
14 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
15 SYSTEMPATH\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
16 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
19 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-02-15 15:36:06 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption in C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php:78
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 78)
#1 C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php(78): pg_connect('host=172.16.225...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\ci4\app\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\app\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
#7 C:\xampp\htdocs\ci4\system\Config\Factories.php(235): Config\Database->__construct()
#8 C:\xampp\htdocs\ci4\system\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', Array)
#9 C:\xampp\htdocs\ci4\system\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', Array)
#10 C:\xampp\htdocs\ci4\system\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
#11 C:\xampp\htdocs\ci4\system\Database\Config.php(63): config('Config\\Database')
#12 C:\xampp\htdocs\ci4\app\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
#13 C:\xampp\htdocs\ci4\app\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
#14 C:\xampp\htdocs\ci4\app\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
#15 C:\xampp\htdocs\ci4\app\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
#16 C:\xampp\htdocs\ci4\system\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
#17 C:\xampp\htdocs\ci4\system\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
#18 C:\xampp\htdocs\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 C:\xampp\htdocs\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 C:\xampp\htdocs\ci4\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}
CRITICAL - 2025-02-15 15:36:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption
[Method: GET, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "company_database_config"
WHERE "company_name" = :company_name:', [...], false)
 3 APPPATH\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
 5 SYSTEMPATH\Config\Factories.php(235): Config\Database->__construct()
 6 SYSTEMPATH\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', [])
 7 SYSTEMPATH\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
 9 SYSTEMPATH\Database\Config.php(63): config('Config\\Database')
10 APPPATH\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
11 APPPATH\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
12 APPPATH\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
13 APPPATH\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
14 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
15 SYSTEMPATH\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
16 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
19 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-02-15 15:59:07 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption in C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php:78
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 78)
#1 C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php(78): pg_connect('host=172.16.225...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\ci4\app\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\app\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
#7 C:\xampp\htdocs\ci4\system\Config\Factories.php(235): Config\Database->__construct()
#8 C:\xampp\htdocs\ci4\system\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', Array)
#9 C:\xampp\htdocs\ci4\system\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', Array)
#10 C:\xampp\htdocs\ci4\system\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
#11 C:\xampp\htdocs\ci4\system\Database\Config.php(63): config('Config\\Database')
#12 C:\xampp\htdocs\ci4\app\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
#13 C:\xampp\htdocs\ci4\app\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
#14 C:\xampp\htdocs\ci4\app\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
#15 C:\xampp\htdocs\ci4\app\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
#16 C:\xampp\htdocs\ci4\system\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
#17 C:\xampp\htdocs\ci4\system\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
#18 C:\xampp\htdocs\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 C:\xampp\htdocs\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 C:\xampp\htdocs\ci4\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}
CRITICAL - 2025-02-15 15:59:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption
[Method: GET, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "company_database_config"
WHERE "company_name" = :company_name:', [...], false)
 3 APPPATH\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
 5 SYSTEMPATH\Config\Factories.php(235): Config\Database->__construct()
 6 SYSTEMPATH\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', [])
 7 SYSTEMPATH\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
 9 SYSTEMPATH\Database\Config.php(63): config('Config\\Database')
10 APPPATH\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
11 APPPATH\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
12 APPPATH\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
13 APPPATH\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
14 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
15 SYSTEMPATH\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
16 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
19 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-02-15 15:59:14 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption in C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php:78
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 78)
#1 C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php(78): pg_connect('host=172.16.225...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\ci4\app\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\app\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
#7 C:\xampp\htdocs\ci4\system\Config\Factories.php(235): Config\Database->__construct()
#8 C:\xampp\htdocs\ci4\system\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', Array)
#9 C:\xampp\htdocs\ci4\system\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', Array)
#10 C:\xampp\htdocs\ci4\system\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
#11 C:\xampp\htdocs\ci4\system\Database\Config.php(63): config('Config\\Database')
#12 C:\xampp\htdocs\ci4\app\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
#13 C:\xampp\htdocs\ci4\app\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
#14 C:\xampp\htdocs\ci4\app\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
#15 C:\xampp\htdocs\ci4\app\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
#16 C:\xampp\htdocs\ci4\system\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
#17 C:\xampp\htdocs\ci4\system\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
#18 C:\xampp\htdocs\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 C:\xampp\htdocs\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 C:\xampp\htdocs\ci4\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}
CRITICAL - 2025-02-15 15:59:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption
[Method: GET, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "company_database_config"
WHERE "company_name" = :company_name:', [...], false)
 3 APPPATH\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
 5 SYSTEMPATH\Config\Factories.php(235): Config\Database->__construct()
 6 SYSTEMPATH\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', [])
 7 SYSTEMPATH\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
 9 SYSTEMPATH\Database\Config.php(63): config('Config\\Database')
10 APPPATH\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
11 APPPATH\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
12 APPPATH\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
13 APPPATH\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
14 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
15 SYSTEMPATH\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
16 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
19 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-02-15 16:03:49 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption in C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php:78
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 78)
#1 C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php(78): pg_connect('host=172.16.225...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\ci4\app\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\app\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
#7 C:\xampp\htdocs\ci4\system\Config\Factories.php(235): Config\Database->__construct()
#8 C:\xampp\htdocs\ci4\system\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', Array)
#9 C:\xampp\htdocs\ci4\system\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', Array)
#10 C:\xampp\htdocs\ci4\system\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
#11 C:\xampp\htdocs\ci4\system\Database\Config.php(63): config('Config\\Database')
#12 C:\xampp\htdocs\ci4\app\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
#13 C:\xampp\htdocs\ci4\app\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
#14 C:\xampp\htdocs\ci4\app\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
#15 C:\xampp\htdocs\ci4\app\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
#16 C:\xampp\htdocs\ci4\system\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
#17 C:\xampp\htdocs\ci4\system\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
#18 C:\xampp\htdocs\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 C:\xampp\htdocs\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 C:\xampp\htdocs\ci4\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}
CRITICAL - 2025-02-15 16:03:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption
[Method: GET, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "company_database_config"
WHERE "company_name" = :company_name:', [...], false)
 3 APPPATH\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
 5 SYSTEMPATH\Config\Factories.php(235): Config\Database->__construct()
 6 SYSTEMPATH\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', [])
 7 SYSTEMPATH\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
 9 SYSTEMPATH\Database\Config.php(63): config('Config\\Database')
10 APPPATH\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
11 APPPATH\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
12 APPPATH\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
13 APPPATH\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
14 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
15 SYSTEMPATH\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
16 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
19 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-02-15 16:03:52 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption in C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php:78
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 78)
#1 C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php(78): pg_connect('host=172.16.225...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\ci4\app\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\app\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
#7 C:\xampp\htdocs\ci4\system\Config\Factories.php(235): Config\Database->__construct()
#8 C:\xampp\htdocs\ci4\system\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', Array)
#9 C:\xampp\htdocs\ci4\system\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', Array)
#10 C:\xampp\htdocs\ci4\system\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
#11 C:\xampp\htdocs\ci4\system\Database\Config.php(63): config('Config\\Database')
#12 C:\xampp\htdocs\ci4\app\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
#13 C:\xampp\htdocs\ci4\app\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
#14 C:\xampp\htdocs\ci4\app\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
#15 C:\xampp\htdocs\ci4\app\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
#16 C:\xampp\htdocs\ci4\system\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
#17 C:\xampp\htdocs\ci4\system\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
#18 C:\xampp\htdocs\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 C:\xampp\htdocs\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 C:\xampp\htdocs\ci4\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}
CRITICAL - 2025-02-15 16:03:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption
[Method: GET, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "company_database_config"
WHERE "company_name" = :company_name:', [...], false)
 3 APPPATH\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
 5 SYSTEMPATH\Config\Factories.php(235): Config\Database->__construct()
 6 SYSTEMPATH\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', [])
 7 SYSTEMPATH\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
 9 SYSTEMPATH\Database\Config.php(63): config('Config\\Database')
10 APPPATH\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
11 APPPATH\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
12 APPPATH\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
13 APPPATH\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
14 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
15 SYSTEMPATH\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
16 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
19 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-02-15 16:04:31 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption in C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php:78
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 78)
#1 C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php(78): pg_connect('host=172.16.225...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\ci4\app\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\app\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
#7 C:\xampp\htdocs\ci4\system\Config\Factories.php(235): Config\Database->__construct()
#8 C:\xampp\htdocs\ci4\system\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', Array)
#9 C:\xampp\htdocs\ci4\system\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', Array)
#10 C:\xampp\htdocs\ci4\system\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
#11 C:\xampp\htdocs\ci4\system\Database\Config.php(63): config('Config\\Database')
#12 C:\xampp\htdocs\ci4\app\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
#13 C:\xampp\htdocs\ci4\app\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
#14 C:\xampp\htdocs\ci4\app\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
#15 C:\xampp\htdocs\ci4\app\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
#16 C:\xampp\htdocs\ci4\system\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
#17 C:\xampp\htdocs\ci4\system\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
#18 C:\xampp\htdocs\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 C:\xampp\htdocs\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 C:\xampp\htdocs\ci4\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}
CRITICAL - 2025-02-15 16:04:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption
[Method: GET, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "company_database_config"
WHERE "company_name" = :company_name:', [...], false)
 3 APPPATH\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
 5 SYSTEMPATH\Config\Factories.php(235): Config\Database->__construct()
 6 SYSTEMPATH\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', [])
 7 SYSTEMPATH\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
 9 SYSTEMPATH\Database\Config.php(63): config('Config\\Database')
10 APPPATH\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
11 APPPATH\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
12 APPPATH\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
13 APPPATH\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
14 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
15 SYSTEMPATH\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
16 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
19 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-02-15 16:04:32 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption in C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php:78
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 78)
#1 C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php(78): pg_connect('host=172.16.225...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\ci4\app\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\app\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
#7 C:\xampp\htdocs\ci4\system\Config\Factories.php(235): Config\Database->__construct()
#8 C:\xampp\htdocs\ci4\system\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', Array)
#9 C:\xampp\htdocs\ci4\system\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', Array)
#10 C:\xampp\htdocs\ci4\system\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
#11 C:\xampp\htdocs\ci4\system\Database\Config.php(63): config('Config\\Database')
#12 C:\xampp\htdocs\ci4\app\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
#13 C:\xampp\htdocs\ci4\app\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
#14 C:\xampp\htdocs\ci4\app\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
#15 C:\xampp\htdocs\ci4\app\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
#16 C:\xampp\htdocs\ci4\system\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
#17 C:\xampp\htdocs\ci4\system\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
#18 C:\xampp\htdocs\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 C:\xampp\htdocs\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 C:\xampp\htdocs\ci4\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}
CRITICAL - 2025-02-15 16:04:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption
[Method: GET, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "company_database_config"
WHERE "company_name" = :company_name:', [...], false)
 3 APPPATH\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
 5 SYSTEMPATH\Config\Factories.php(235): Config\Database->__construct()
 6 SYSTEMPATH\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', [])
 7 SYSTEMPATH\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
 9 SYSTEMPATH\Database\Config.php(63): config('Config\\Database')
10 APPPATH\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
11 APPPATH\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
12 APPPATH\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
13 APPPATH\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
14 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
15 SYSTEMPATH\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
16 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
19 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-02-15 16:05:38 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption in C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php:78
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 78)
#1 C:\xampp\htdocs\ci4\system\Database\Postgre\Connection.php(78): pg_connect('host=172.16.225...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\ci4\app\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\app\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
#7 C:\xampp\htdocs\ci4\system\Config\Factories.php(235): Config\Database->__construct()
#8 C:\xampp\htdocs\ci4\system\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', Array)
#9 C:\xampp\htdocs\ci4\system\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', Array)
#10 C:\xampp\htdocs\ci4\system\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
#11 C:\xampp\htdocs\ci4\system\Database\Config.php(63): config('Config\\Database')
#12 C:\xampp\htdocs\ci4\app\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
#13 C:\xampp\htdocs\ci4\app\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
#14 C:\xampp\htdocs\ci4\app\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
#15 C:\xampp\htdocs\ci4\app\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
#16 C:\xampp\htdocs\ci4\system\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
#17 C:\xampp\htdocs\ci4\system\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
#18 C:\xampp\htdocs\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 C:\xampp\htdocs\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 C:\xampp\htdocs\ci4\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}
CRITICAL - 2025-02-15 16:05:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no pg_hba.conf entry for host &quot;172.16.225.129&quot;, user &quot;postgres&quot;, database &quot;sinha&quot;, no encryption
[Method: GET, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "company_database_config"
WHERE "company_name" = :company_name:', [...], false)
 3 APPPATH\Config\Database.php(81): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Config\Database.php(41): Config\Database->getDatabaseDetailsFromMaster('company1')
 5 SYSTEMPATH\Config\Factories.php(235): Config\Database->__construct()
 6 SYSTEMPATH\Config\Factories.php(169): CodeIgniter\Config\Factories::createInstance('config', 'Config\\Database', [])
 7 SYSTEMPATH\Config\Factories.php(188): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Common.php(210): CodeIgniter\Config\Factories::get('config', 'Config\\Database')
 9 SYSTEMPATH\Database\Config.php(63): config('Config\\Database')
10 APPPATH\Models\Auth\UserModel.php(25): CodeIgniter\Database\Config::connect('database2')
11 APPPATH\Repositories\Auth\UserRepository.php(13): App\Models\Auth\UserModel->__construct()
12 APPPATH\Services\Auth\UserService.php(13): App\Repositories\Auth\UserRepository->__construct()
13 APPPATH\Controllers\Auth\LoginController.php(28): App\Services\Auth\UserService->__construct()
14 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Auth\LoginController->__construct()
15 SYSTEMPATH\CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
16 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
19 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-02-15 16:24:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-02-15 16:24:54 --> Predis\Connection\ConnectionException: No connection could be made because the target machine actively refused it [tcp://127.0.0.1:6379]
[Method: POST, Route: auth/login]
in VENDORPATH\predis\predis\src\Connection\AbstractConnection.php on line 144.
 1 VENDORPATH\predis\predis\src\Connection\StreamConnection.php(109): Predis\Connection\AbstractConnection->onConnectionError('No connection could be made because the target machine actively refused it', 10061)
 2 VENDORPATH\predis\predis\src\Connection\StreamConnection.php(154): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://127.0.0.1:6379', 4)
 3 VENDORPATH\predis\predis\src\Connection\StreamConnection.php(80): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))
 4 VENDORPATH\predis\predis\src\Connection\AbstractConnection.php(85): Predis\Connection\StreamConnection->createResource()
 5 VENDORPATH\predis\predis\src\Connection\StreamConnection.php(230): Predis\Connection\AbstractConnection->connect()
 6 VENDORPATH\predis\predis\src\Connection\AbstractConnection.php(169): Predis\Connection\StreamConnection->connect()
 7 VENDORPATH\predis\predis\src\Connection\StreamConnection.php(265): Predis\Connection\AbstractConnection->getResource()
 8 VENDORPATH\predis\predis\src\Connection\StreamConnection.php(372): Predis\Connection\StreamConnection->write('*4
$5
SETEX
$12
user_1_links
$4
6000
$146
["hr\\/employees","hr\\/employees\\/create","hr\\/employees\\/store","hr\\/employees\\/edit","hr\\/employees\\/update","hr\\/employees\\/delete","dashboard"]
')
 9 VENDORPATH\predis\predis\src\Connection\AbstractConnection.php(122): Predis\Connection\StreamConnection->writeRequest(Object(Predis\Command\Redis\SETEX))
10 VENDORPATH\predis\predis\src\Client.php(381): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\Redis\SETEX))
11 VENDORPATH\predis\predis\src\Client.php(335): Predis\Client->executeCommand(Object(Predis\Command\Redis\SETEX))
12 APPPATH\Controllers\Auth\LoginController.php(88): Predis\Client->__call('setex', [...])
13 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth\LoginController->login()
14 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\LoginController))
15 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
16 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
17 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
18 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-02-15 16:30:51 --> Predis\Connection\ConnectionException: Error while reading line from the server. [tcp://172.16.225.1:6379]
[Method: POST, Route: auth/login]
in VENDORPATH\predis\predis\src\Connection\AbstractConnection.php on line 144.
 1 VENDORPATH\predis\predis\src\Connection\StreamConnection.php(291): Predis\Connection\AbstractConnection->onConnectionError('Error while reading line from the server.')
 2 VENDORPATH\predis\predis\src\Connection\AbstractConnection.php(132): Predis\Connection\StreamConnection->read()
 3 VENDORPATH\predis\predis\src\Connection\AbstractConnection.php(124): Predis\Connection\AbstractConnection->readResponse(Object(Predis\Command\Redis\SETEX))
 4 VENDORPATH\predis\predis\src\Client.php(381): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\Redis\SETEX))
 5 VENDORPATH\predis\predis\src\Client.php(335): Predis\Client->executeCommand(Object(Predis\Command\Redis\SETEX))
 6 APPPATH\Controllers\Auth\LoginController.php(89): Predis\Client->__call('setex', [...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth\LoginController->login()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-02-15 16:32:00 --> Simple value successfully saved to Redis with key: user_1_links
DEBUG - 2025-02-15 16:32:00 --> Retrieved simple cached value: ["hr\/employees","hr\/employees\/create","hr\/employees\/store","hr\/employees\/edit","hr\/employees\/update","hr\/employees\/delete","dashboard"]
DEBUG - 2025-02-15 16:32:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-02-15 16:32:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-02-15 16:32:00 --> Retrieved simple cached value: AuthFilter: ["hr\/employees","hr\/employees\/create","hr\/employees\/store","hr\/employees\/edit","hr\/employees\/update","hr\/employees\/delete","dashboard"]
